# Generated by Django 4.2.6 on 2023-10-10 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=8)),
                ('items', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('ref_id', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=255)),
                ('transaction_when', models.DateTimeField(null=True)),
                ('payment_link_id', models.CharField(max_length=255, null=True)),
                ('transaction_code', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('webhook_snapshot', models.TextField(max_length=65535, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
